name: pcos_assessment_tools
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  typewritertext: ^3.0.9
  percent_indicator: ^4.2.2
  http: ^1.2.2
  flutter_svg: ^2.0.14
  url_launcher: ^6.1.6
  google_fonts: ^6.2.1
  pdf: ^3.11.1




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/A.Menstrual Irregularities/
    - assets/B.Hirsutism/
    - assets/C.Acne and Skin Conditions/
    - assets/D. Weight and Metabolic Factors/
    - assets/E. Family History/
    - assets/B.Hirsutism/300ppi/
    - assets/ui/
    - assets/
  fonts:
    - family: Noto Color Emoji
      fonts:
        - asset: assets/NotoColorEmoji-Regular.ttf

